version: '3.8'

services:
  fastapi-blog:
    build: .
    container_name: fastapi-blog-app
    ports:
      - "8000:8000"
    volumes:
      # Mount volume for SQLite database persistence
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/blog"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: fastapi-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi-blog
    restart: unless-stopped
    profiles:
      - with-nginx

networks:
  default:
    name: fastapi-blog-network
